artifacts_roots: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/allu0786ansari/Data_Used_In_Project/raw/main/samsumdata%20-Text%20Summarization.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion